* 云计算基础介绍
** EDC
   EDC（Enterprise Data Center）企业级数据中心；指企业自建自行运维。稳定性要求较高，到采用相对成熟的技术。
*** 自建机房
**** 数据中心分层
     L4：业务应用层（各种应用系统（ERP、CRM、OA系统等））
     L3：应用支撑层（中间件、消息调度、集成开发环境、API/SDK等）
         数据分析层（数据库、数据仓库、BI系统）
     L2：IT基础设施层（服务器、网络、存储、安全等）
     L1：机房设施层（电源、制冷、机柜、布线等）
     L0：楼宇系统层（机房、传输、安保、防火等）
***** 面临的挑战
      - 建设难度高、运维管理复杂
      - 扩展调整不便、上线周期长
***** TCO总拥有成本较高
      TCO = CapEx + OpEx + OppCost
      - TCO
        总拥有成本，包括产品采购到后期使用、维护的成本。这是一种公司经常采用的技术评价标准。
      - CapEx 资本支出
          Capital Expenditure，资本性支出；
          初期购买支出（硬件、软件和服务包），以及后期随着企业发展，网络的升级扩容投入等。
      - OpEx 运维成本
        Operating Expense
        日常网络运行维护有关的简介成本，包括安装、调试、维护、管理以及培训。其他类型的运维成本还包括机房租金，电费等。
      - OppCost 机会成本
        不可见、更难量化的不分，例如因关键网络设备故障所引起的营收损失，不能快速承载新业务来满足客户的新需求而导致的利润流失等。
        其他机会成本还包括因系统崩溃造成的生产力损失，因不能及时补救而错失的商业机会等。
***** TVO总拥有价值不明显
      TVO = IT带来的业务价值与收益
**** 承担的工作
     - 规划建设类
       机房的建设、土建施工、机柜摆放、UPS供电、精密空调温度调整
     - 部署类
       服务器、存储、网络等物理设备的上架和安装、基础架构部署运维、业务系统部署等
     - 运维类
       安全运维、可用性、可靠性管理
**** 挑战
     - 承担服务器、存储、网络等硬件资源的成本，又要承担高昂的专线网络费用，同时场地、电力、空调、日常维护机房管理等各种开销居高不下
     - 保证365天全天候运营服务，既需要充分的专业技术人员负责设备的维护，有效的保障网络的稳定性；
       又需要多路供电实现电力持续供应保证，以及备份发电机、24小时运作的机房专用空调系统等标准设施
       同时还需要保证稳定的网络带宽、恒温、防尘、防火、防潮、防静电等良好的运行环境
*** 数据中心等级T1~T4
    - 可靠性、安全性
    - 运维管理能力
    - 基础设施可用性
      可用性=(承诺服务时间-宕机时间) / 承诺服务时间 * 100%
    | +      | +        |       + | +        |
    | DC等级 | 说明     |  可用性 |          |
    | T4     | 双活容错 | 99.995% | 0.8小时  |
    | T3     | 并行维护 | 99.982% | 1.6小时  |
    | T2     | 冗余组件 | 99.741% | 22.0小时 |
    | T1     | 基本容量 | 99.671% | 28.8小时   |
** IDC
   IDC（Internet Data Center）互联网服务的数据中心；通常以第三方托管形式出现，平台应用云大量部署。
*** 服务
    - 基础平台服务
      服务器托管、虚拟主机、邮件缓存、虚拟邮件等
    - 增值服务
      场地的租用服务、域名系统服务、负载均衡系统、数据库系统、数据备份服务等
